# Generated by Django 5.2 on 2026-03-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0005_add_instructor_quiz_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=1, help_text='Number of questions in this quiz'),
        ),
    ]
